# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/User/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-14232-RagnarMSI/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/RISCV_Core/RISCV_Core.cache/wt} [current_project]
set_property parent.project_path {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/RISCV_Core/RISCV_Core.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.4 [current_project]
set_property ip_output_repo {c:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/RISCV_Core/RISCV_Core.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/ALU.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/ALU_CU.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/ALU_InMux.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/ALU_OutMux.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/Branch_Logic_Unit.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/Control_FSM.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/DATA_MEMORY.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/INST_MEMORY.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/Immediate_Generation.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/PC_Inc.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/PC_Mux.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/Program_Counter.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/Reg_File_Input.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/Register_File.sv}
  {C:/Users/User/Downloads/Documents/ACA/Sem 5/EN3030 Circuits and Systems Design/Vivado/src/RISCV_Processor.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top RISCV_Processor -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_Processor_utilization_synth.rpt -pb RISCV_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
